parameters:
  contao_import.legacy_database_url: '%env(default::LEGACY_DATABASE_URL)%'
  contao_import.column_map:
    tl_news_archive: { }
    tl_news: { }
    tl_content: { }
  contao_import.fixed_values:
    tl_content:
      ptable: 'tl_news'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  webfarben\ContaoImport\:
    resource: '../src/*'
    exclude:
      - '../src/ContaoManager/'
      - '../src/DependencyInjection/'
      - '../src/Resources/'
      - '../src/ContaoImportBundle.php'

  webfarben\ContaoImport\Import\LegacyConnectionFactory:
    public: true
    arguments:
      $databaseUrl: '%contao_import.legacy_database_url%'

  webfarben\ContaoImport\Import\NewsImporter:
    public: true
    arguments:
      $columnMap: '%contao_import.column_map%'
      $fixedValues: '%contao_import.fixed_values%'
